### ISSUE TITLE
Implement MD Docs to be housed in Dijnn Repo

### ISSUE THREAD

**Issue by bamccaul-dev** [Pageworks/djinnjs#68]
We need to move the documentation for Djinn to utilize dev-docks for output of documentation on local dev devices.

**Comment by codewithkyle** [comment]
Dev Docs package [v0.1.6](https://github.com/codewithkyle/dev-docs/releases/tag/v0.1.6) has been released. Docs can be output as static HTML files by adding the `-o ./output-dir-path` flag. Using this feature alongside the [gh-pages](https://www.npmjs.com/package/gh-pages) package will allow us to build & deploy DjinnJS documentation to this repos `gh-pages` branch via GitHub Actions.
