### ISSUE TITLE
Web Worker Thread Pool

### ISSUE THREAD

**Issue by codewithkyle** [Pageworks/djinnjs#71]
### Concept 

The `Env` class should calculate how many workers we are allowed to register.

Developers can request permission to register a new worker and as `high` or `low` priority. If the pool limit has been reached a low priority worker is terminated. If there are no low priority workers to be terminated the system should break & throw errors informing the developer of the issue.

It is on the developer to determine how to split the work between the workers, the priority levels, and the minimum device specs the application can support.

### References
https://en.wikipedia.org/wiki/Service_locator_pattern
https://en.wikipedia.org/wiki/Dependency_injection
https://en.wikipedia.org/wiki/Factory_(object-oriented_programming)

**Comment by codewithkyle** [comment]
### Why

Why add this? Safari removed support for [Shared Workers](https://caniuse.com/#feat=sharedworkers) and is not currently planning on adding them back. Ideally, general use utility workers could be shared, however, due to incomplete support we need to build a service locator to help manage workers, see the Service Locator Pattern link in the OP for additional details.

**Comment by codewithkyle** [comment]
@bamccaul-dev We will need to discuss our defaults and minimum requirements during our next meeting. Mainly we need to discuss Safari.

> WebKit browsers clamp the maximum value returned to 2 on iOS devices and 8 on all others. 

Also [Hardware Concurrency](https://caniuse.com/#feat=hardwareconcurrency) is supported but  it's returning `undefined` in Safari 13.1 because of this:

> Disabled in Safari behind the ENABLE_NAVIGATOR_HWCONCURRENCY build option.

A workaround could be to load 3rd party libraries or we can discuss the currently supported OSX versions, their support lifecycles, and the devices minimums with the main issue being how we decide to handle Safari on a hackintosh.

**Comment by bamccaul-dev** [comment]
I think, per the conversation in the Djinn weekly meeting, we need to find a single core system, and see how it responds with spinning up several workers. We need to get more information about this will behave and degrades on older hardware. Lee will be providing some old hardware to test on.

**Comment by codewithkyle** [comment]
This feature is not particularly useful until [Safari](https://bugs.webkit.org/show_bug.cgi?id=164860) and [Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1247687) ship support for ES Modules within Web Workers. Until then developers would basically need to write their code twice, first in the worker then again in a controller for the UI thread.

**Comment by codewithkyle** [comment]
Although I still believe this is could be a useful enhancement I've decided to close this issue. Most likely we will not be hitting the Web Worker limit for 99.99% of our users on any typical projects. The projects that require several workers would most likely be a PWA built for internal use or for a client where it would be easier to dictate the minimum device specs for the software. Once `new Worker( 'my-worker.js', { type : 'module' } );` is supported by all major browsers we can reconsider building this feature.
