### ISSUE TITLE
CDN and Dynamic loading

### ISSUE THREAD

**Issue by bamccaul-dev** [Pageworks/djinnjs#84]
We need to investigate how well the dynamic loading works with Djinn, and if there are any further optimizations that can take place with a CDN such as CloudFlare.

**Comment by codewithkyle** [comment]
I'm not sure where we left off on this one. Here's what I know:

Djinn handles client-side caching so the question of "CDN vs no CDN" really depends on the server stack and what operations are happening before a response it sent. Djinn will hit whatever IP address the DNS points too.

**Comment by codewithkyle** [comment]
As a test I put my [portfolio website](https://kyleandrews.dev/) behind the Cloudflare CDN free tier and everything works as expected. My TTBF drops from ~26ms to ~18ms when the CDN cache is enabled.
