### ISSUE TITLE
Remove Broadcaster from core and make as a peer dependency

### ISSUE THREAD

**Issue by codewithkyle** [Pageworks/djinnjs#95]
I'm struggling to remember why we **need** a broadcaster. I know WWIBS can help communicate between Web Components and IIFE wrapped component libraries like Preact but I don't know why we need it in Djinn. It seems to solve the same problem as import statements.

With WWIBS sending a message becomes a messy process as different components begin pinging messages back and forth. It's hard to read and debug compared to imported functions and classes.

In Djinn we can write a controller that imports a web component and register's it within the constructor. Within the web component connected callback we can call a public function imported from the controller that links the instance by passing a reference to the web components DOM node. Once everything (views/web workers) have registered the controller could call an init method and begin managing the application state. Data can be passed using function calls. Along with easier debugging we can begin to provide inline documentation using jsdocs.

The only downside I can see is that we lose the pjax completed message. However, so far the only time I know we've hooked into the completed message is to style a navigation link based on the new pages URL. In my opinion loading several KBs of extra JavaScript just to underline a link is a waste of the users data and an unnecessary Lighthouse performance hit. We could leverage the CustomEvent API for this since it's easy to use and native.

**Comment by codewithkyle** [comment]
It's also worth noting that anytime several components are messaging each other a controller is usually created to maintain order, dictate the application state, and handle any API calls. Forcing the usage of a manager class anytime two or more components need to communicate doesn't seem like a bad idea to me.

**Comment by bamccaul-dev** [comment]
I think that this is a good idea in general. We need to keep Djinn as the JS boostrapper that it should be. There is a related issue to this #98 that came from the Zoom discussion about it. In the end, we can have this be an entirely optional setup for each site/project.
